### ISSUE TITLE
Feature images for Assessment idea page

### ISSUE THREAD

**Issue by chloecwh** [TWUOnline/multi-access#17]
Hi @meher-ahmed  

Can you help bring the feature image on the [old site](https://multi-access.twu.ca/assessment/assessment-ideas) to the new [assessment page](https://create.twu.ca/multi-access/defining-assessment/assessment-ideas/)? 

The images from the old site can be added to the feature image column on the right hand size, see attached screenshot.  
![Screenshot 2024-03-06 at 3 13 58 PM](https://github.com/TWUOnline/multi-access/assets/150065592/1154d653-aa82-4572-95ad-7135fd04f8b8)

**Comment by chloecwh** [comment]
Hi @cmadland, can you help assign Meher to this issue? She's part of the organization but I can't assign her to this task. Thanks! 

About adding her to Wordpress, should I add @twu.ca or a personal gmail account?

**Comment by cmadland** [comment]
> Hi @cmadland, can you help assign Meher to this issue? She's part of the organization but I can't assign her to this task. Thanks!
> 
> About adding her to Wordpress, should I add @twu.ca or a personal gmail account?

Meher needs to be added to individual repos, not just the organization.

**Comment by chloecwh** [comment]
@meher-ahmed Any updates on this task?

**Comment by Jeff-TWU** [comment]
[Updated](https://create.twu.ca/multi-access/defining-assessment/assessment-ideas/)

**Comment by chloecwh** [comment]
Thanks @Jeff-TWU
